/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  // "aws_project_region": "eu-central-1",
  // // APP SYNC
  // "aws_appsync_graphqlEndpoint": "https://43wiclb5jjaf3o6ag74agzauwm.appsync-api.eu-central-1.amazonaws.com/graphql",
  // "aws_appsync_region": "eu-central-1",
  // "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS", // authenticate users via user pool
  // "aws_appsync_apiKey": "null",
  // // COGNITO
  // "aws_cognito_identity_pool_id": "eu-central-1:d13fcd98-2a70-4f49-b8ea-2863799b4c1b", // identity pool id
  // "aws_cognito_region": "eu-central-1",
  // "aws_user_pools_id": "eu-central-1_gEkchIXEH", // user pool id
  // "aws_user_pools_web_client_id": "7figndr0uujlbv4aoj17iqbngg", // user pool app client id
  // // AUTH FLOW
  // "oauth": {}, // none
  // // S3 STORAGE
  // "aws_user_files_s3_bucket": "vvgbffdcd15636e4fa1b27e35d81c2b420c205453-dev", // bucket name
  // "aws_user_files_s3_bucket_region": "eu-central-1"

    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:d13fcd98-2a70-4f49-b8ea-2863799b4c1b",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_gEkchIXEH",
    "aws_user_pools_web_client_id": "7figndr0uujlbv4aoj17iqbngg",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://43wiclb5jjaf3o6ag74agzauwm.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  // "aws_user_files_s3_bucket": "vvgbffdcd15636e4fa1b27e35d81c2b420c205453-dev", // bucket name
  // "aws_user_files_s3_bucket_region": "eu-central-1""
};


export default awsmobile;
